site_name: Site
site_url: https://example.com/

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
      smart_dollar: false
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - toc:                          # Table des matières générée automatiquement à partir des titres du niveau 2
        permalink: "&num;"          # Ajoute un symbole lien hypertexte vers l'ancre du titre #le-titre 
        toc_depth: 4
  - tables

  

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - stylesheets/extra.css 
  

nav:
    - Home: index.md
    - About: about.md
    - 'Première':
      - Neumann : Premiere/neumann.md
      - web : Premiere/web_1NSI.md
    - 'Terminale':
      - SOC : Terminale/cours.md
      - Récursivité : Terminale/recursivite.md
    - index2 : index2.html
    - anglais4 : anglais4.md
    
    

